cmd_leader = "BW,"
welcome_msgs = [
  "Welcome to the server, {name}",
  "Get-a-blockin, {name}",
  "Did it hurt, {name}? When you fell from heaven?",
  "Shouldn't you be doing something more productive, {name}?",
  "What about that lab report, {name}",
  "{name}! Have you completed your health and safety quiz?",
  "{name}, what are you doing here at this hour?",
  "Have fun {name}! Just not too much...",
  "Everyone on your best behaviour! {name} has joined the game.",
  "Why is it when something happens, it's always you, {name}?",
  "All hail lord {name}!",
  "I'm always watching, {name}...",
  "Why are we here, {name}? Just to suffer?",
  "Oh, {name}, it's you again...",
  "Hello {name} and welcome to Notch's wet and wild adventure!",
  "May the blessings of Watersheep be upon you, {name}",
  "Please refrain from naughty words in my Christian Minecraft server, {name}",
  "Are these messages targeted? Or just random? You tell me, {name}...",
  "The sky turns dark and the birds drop silent. {name} has finally come.",
  "It's as the legends foretold! {name} has joined the game!",
  "Welcome home, {name}",
]